<?php
$lang_data = array(
	'dashboard'=>'Dashboard',
	'post_ads'=>'Post Ads',
	'logout'=>'Logout',
	'lOGIN'=>'LOGIN',
	'sign_up'=>'SIGN UP',
	'you_have_selected'=>'You have selected',
	'lang_text1'=>'WHAT ARE YOU LOOKING FOR?',
	'lang_text2'=>'Search by cars, houses etc.',
	'enter_location'=>'Enter location',
	'search'=>'Search',
	'prove_you_are_not_robort.'=>'Prove you are not robort.',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
);
?>